# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.1"
  config.vm.synced_folder "..", "/vagrant" # the parent folder is where we do the real deployment.
  config.vm.synced_folder "../../../", "/alluxio" #sync local alluxio to VM, added By Chi-fan Chu
  config.vm.synced_folder "../../../../AlluxioBasicIOTest", "/AlluxioBasicIOTest" #added by Chi-fan Chu
  config.vm.provision "ansible" do |ans|
    ans.playbook = "../provision/playbook-basic.yml"
  end
end
